version: 2
aliases:
  cache:
    lib_cache: &CACHE
      key: lein-{{ checksum "project.clj" }}
      paths:
      - ~/.lein
      - ~/.m2
      - node_modules
  containers:
    docker: &DEFAULT
    - image: jesiio/build-bus:latest
      environment:
        JVM_OPTS: -Xmx3200m
        DEBUG: 1
jobs:
  deps:
    docker: *DEFAULT
    steps:
    - checkout
    - restore_cache:
        <<: *CACHE
    - run: './stone.sh deps'
    - save_cache:
        <<: *CACHE
  test_cljs:
    docker: *DEFAULT
    steps:
    - checkout
    - restore_cache:
        <<: *CACHE
    - run: './stone.sh unit-test'
    - save_cache:
        <<: *CACHE
workflows:
  version: 2
  build:
    jobs:
    - deps
    - test_cljs:
        requires:
        - deps
